# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('each', 'each')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreppedMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PreppedMealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateField(blank=True, null=True)),
                ('best_before', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreppedMealTypeIngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Ingredient')),
                ('prepped_meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.PreppedMealType')),
            ],
        ),
        migrations.AddField(
            model_name='preppedmealtype',
            name='ingredients',
            field=models.ManyToManyField(through='foods.PreppedMealTypeIngredientQuantity', to='foods.Ingredient'),
        ),
        migrations.AddField(
            model_name='preppedmeal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.PreppedMealType'),
        ),
    ]
